### ISSUE TITLE
opc_lbaas_server_pool causes panic

### ISSUE THREAD

**Issue by adormanau** [terraform-providers/terraform-provider-opc#142]
When creating a opc_lbaas_server_pool we receive a panic.

This is configured in the common/modules/lbr/portal/main.tf. Reference by nonprod/main.tf

### Terraform Version
Terraform v0.11.7
+ provider.opc v1.2.0

### Affected Resource(s)
- opc_lbaas_server_pool

### Terraform Configuration Files
https://www.dropbox.com/s/qqq3a8tso4hhz1e/terraform.tar.gz.gpg?dl=0

### Debug Output
https://gist.github.com/adormanau/ef2089515b984a2128b0541f23b8f3fe

### Panic Output
https://gist.github.com/adormanau/ed92cd0c50c34be3d2e1da096ce61656

### Expected Behavior
It creates the Load Balancer Server Pool

### Actual Behavior
It crashes with a panic

### Steps to Reproduce
Update terraform.tfvars and provide one or more public keys for the instances

Run the create mgmt 
1. cd mgmt
2. terraform apply -var-file=../terraform.tfvars

Then create the nonprod (with the server pool commented out)
1 cd nonprod
2. terraform apply -var-file=../terraform.tfvars

Then create the server pool (uncomment it)
1 cd nonprod
2. terraform apply -var-file=../terraform.tfvars

1. `terraform apply`

**Comment by scross01** [comment]
Panic details from the logs:

```
2018-07-25T14:37:30.756+1000 [DEBUG] plugin.terraform-provider-opc_v1.2.0_x4: panic: runtime error: index out of range
2018-07-25T14:37:30.756+1000 [DEBUG] plugin.terraform-provider-opc_v1.2.0_x4: 
2018-07-25T14:37:30.756+1000 [DEBUG] plugin.terraform-provider-opc_v1.2.0_x4: goroutine 255 [running]:
2018-07-25T14:37:30.756+1000 [DEBUG] plugin.terraform-provider-opc_v1.2.0_x4: github.com/terraform-providers/terraform-provider-opc/opc.expandOriginServerConfig(0xc420506280, 0x2, 0x2, 0xc420506280, 0x2, 0x2, 0xc42004a7f8, 0x401ee3)
2018-07-25T14:37:30.756+1000 [DEBUG] plugin.terraform-provider-opc_v1.2.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-opc/opc/resource_lbaas_server_pool.go:330 +0x34e
2018-07-25T14:37:30.756+1000 [DEBUG] plugin.terraform-provider-opc_v1.2.0_x4: github.com/terraform-providers/terraform-provider-opc/opc.resourceOriginServerPoolCreate(0xc4202287e0, 0xe3c420, 0xc420263800, 0xc4202287e0, 0x0)
2018-07-25T14:37:30.756+1000 [DEBUG] plugin.terraform-provider-opc_v1.2.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-opc/opc/resource_lbaas_server_pool.go:170 +0x7f5
```

**Comment by scross01** [comment]
Based on the error it looks like the config fails due to an issue with the values provided for the `opc_lbaas_server_pool`  `servers` attribute.  I can't open the config file linked in the issue (the file is gpg encrypted) to confirm - but it looks like the server entry may be missing its port component.

The servers need to be defined as `host:port` or `ipaddress:port` 

e.g. 

```hcl
resource "opc_lbaas_server_pool" "serverpool1" {
  load_balancer = "${opc_lbaas_load_balancer.lb1.id}"
  name          = "serverpool1"

  servers = ["192.168.2.100:8080", "192.168.2.101:8080"]
}
```

An additional check needs to be added to ensure the port component is provided to prevent the panic.

**Comment by adormanau** [comment]
Yes, that was the issue, not including the port with the IP address.

Thanks for helping with this.
